#!/usr/bin/perl

use 5.006;
use strict;
use warnings;

=head1 LICENSE AND COPYRIGHT

Copyright 2013 Bert Vanderbauwhede.

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

See http://www.gnu.org/licenses/ for more information.

=cut
